services:
  site: &base-service
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"
    environment:
      JEKYLL_UID: 1001
      JEKYLL_GID: 1001

  builder:
    <<: *base-service
    command: jekyll build && ls _site
    volumes:
      - ./site:/srv/jekyll/site
